insert into ability (element_id, name) values (9, 'Overgrow');
insert into ability (element_id, name) values (6, 'Blaze');
insert into ability (element_id, name) values (17, 'Torrent');
insert into ability (element_id, name) values (1, 'Shield Dust');
insert into ability (element_id, name) values (1, 'Shed Skin');
insert into ability (element_id, name) values (1, 'Compound Eyes');
insert into ability (element_id, name) values (7, 'Keen Eye');
insert into ability (element_id, name) values (12, 'Tangled Feet');
insert into ability (element_id, name) values (12, 'Guts');
insert into ability (element_id, name) values (12, 'Run Away');
insert into ability (element_id, name) values (13, 'Shed Skin');
insert into ability (element_id, name) values (13, 'Intimidate');
insert into ability (element_id, name) values (4, 'Static');
insert into ability (element_id, name) values (10, 'Send Veil');
insert into ability (element_id, name) values (13, 'Poison Point');
insert into ability (element_id, name) values (13, 'Rivalry');
insert into ability (element_id, name) values (12, 'Cute Charm');
insert into ability (element_id, name) values (12, 'Magic Guard');
insert into ability (element_id, name) values (6, 'Flash Fire');
insert into ability (element_id, name) values (7, 'Inner Focus');
insert into ability (element_id, name) values (9, 'Chlorophyll');
insert into ability (element_id, name) values (1, 'Dry Skin');
insert into ability (element_id, name) values (9, 'Effect Spore');
insert into ability (element_id, name) values (13, 'Tinted Lens');
insert into ability (element_id, name) values (10, 'Arena Trap');
insert into ability (element_id, name) values (12, 'Pickup');
insert into ability (element_id, name) values (12, 'Technician');
insert into ability (element_id, name) values (12, 'Limber');
insert into ability (element_id, name) values (17, 'Cloud Nine');
insert into ability (element_id, name) values (17, 'Damp');
insert into ability (element_id, name) values (5, 'Anger Point');
insert into ability (element_id, name) values (5, 'Vital Spirit');
insert into ability (element_id, name) values (17, 'Water Absorb');
insert into ability (element_id, name) values (14, 'Synchronize');
insert into ability (element_id, name) values (5, 'Guts');
insert into ability (element_id, name) values (5, 'No Guard');
insert into ability (element_id, name) values (17, 'Clear Body');
insert into ability (element_id, name) values (13, 'Liquid Ooze');
insert into ability (element_id, name) values (15, 'Rock Head');
insert into ability (element_id, name) values (10, 'Sturdy');
insert into ability (element_id, name) values (15, 'Sturdy');
insert into ability (element_id, name) values (14, 'Oblivious');
insert into ability (element_id, name) values (14, 'Own Tempo');
insert into ability (element_id, name) values (4, 'Magnet Pull');
insert into ability (element_id, name) values (16, 'Sturdy');
insert into ability (element_id, name) values (7, 'Early Bird');
insert into ability (element_id, name) values (1, 'Swarm');